Squawk:
  Squawk-Prefix: '&2&l *'
  Display-Name-Color: '&b&l'
  Default-ChatColor: '&a'
  Cooldown: 10
Filter:
  Enabled: true
  Swear-Cost: 500
  PlayerPingEnable: true
  PingedPlayerColor: "&5"
  PingSound: BLOCK_END_PORTAL_FRAME_FILL