name: ${project.name}
version: ${project.version}
authors: [Haileykins, CaszGamerMD]
description: Better Chat App. Filter/Replacer/PlayerPinger
main: me.caszgamermd.nootspeak.Main
soft-depend: [TitleManager]

commands:
    squawk:
        description: Base Command, /me type operation.
    nootspeak:
        description: Staff Only Command
        aliases: [ns]
    filter:
        description: Staff Only Command
        aliases: [f, fltr]
    tracker:
        description: Scoreboard Modifier
        aliases: [track]
