name: ${project.name}
version: ${project.version}
description: balls
main: me.caszgamermd.nootspeak.Main

commands:
    squawk:
        description: Base Command, /me type operation
    nootspeak:
        description: Staff only command
        aliases: [ns]